### ISSUE TITLE
Saving album does not work

### ISSUE THREAD

**Issue by mkg20001** [pathephone/pathephone-desktop#180]
When clicking save after adding a bunch of files nothing happens.
The logs also don't say anything interesting.

```
ipfs api running on /ip4/127.0.0.1/tcp/5001
ipfs gateway running on /ip4/127.0.0.1/tcp/8080

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
  music-metadata:parser:ID3 Found ID3v2 header, pos=0 +0ms
  music-metadata:parser:ID3 Found ID3v2 header, pos=0 +2ms
  music-metadata:parser:ID3 Found ID3v2 header, pos=0 +0ms
  music-metadata:parser:ID3 Found ID3v2 header, pos=0 +0ms
  music-metadata:parser:ID3 End of ID3v2 header, go to MPEG-parser: pos=143998 +4ms
  music-metadata:parser:ID3 End of ID3v2 header, go to MPEG-parser: pos=144010 +1ms
  music-metadata:parser:ID3 End of ID3v2 header, go to MPEG-parser: pos=144007 +0ms
  music-metadata:parser:ID3 End of ID3v2 header, go to MPEG-parser: pos=144006 +0ms
  music-metadata:parser:mpeg offset=143998 MP3 bitrate=320000 sample-rate=48000 +0ms
  music-metadata:parser:mpeg offset=144010 MP3 bitrate=320000 sample-rate=48000 +1ms
  music-metadata:parser:mpeg offset=144007 MP3 bitrate=320000 sample-rate=48000 +0ms
  music-metadata:parser:mpeg offset=144006 MP3 bitrate=320000 sample-rate=48000 +0ms
  music-metadata:parser:mpeg offset=144958 MP3 bitrate=320000 sample-rate=48000 +1ms
  music-metadata:parser:mpeg offset=144970 MP3 bitrate=320000 sample-rate=48000 +0ms
  music-metadata:parser:mpeg offset=144967 MP3 bitrate=320000 sample-rate=48000 +1ms
  music-metadata:parser:mpeg offset=144966 MP3 bitrate=320000 sample-rate=48000 +0ms
  music-metadata:parser:mpeg offset=145918 MP3 bitrate=320000 sample-rate=48000 +1ms
  music-metadata:parser:mpeg offset=145930 MP3 bitrate=320000 sample-rate=48000 +0ms
  music-metadata:parser:mpeg offset=145927 MP3 bitrate=320000 sample-rate=48000 +0ms
  music-metadata:parser:mpeg offset=145926 MP3 bitrate=320000 sample-rate=48000 +0ms
  music-metadata:parser:mpeg Calculate CBR duration based on file size: 7.248 +1ms
  music-metadata:parser:mpeg Calculate CBR duration based on file size: 303.48 +0ms
  music-metadata:parser:mpeg Calculate CBR duration based on file size: 390.36 +0ms
  music-metadata:parser:mpeg Calculate CBR duration based on file size: 345.048 +1ms
(node:27037) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by negamaxi** [comment]
@mkg20001 "processing..." screen doesn't appear? In that case, maybe, not all fields filled correctly? Cover, for example, is required.

**Comment by mkg20001** [comment]
@negamaxi Yes, cover was missing. I think it should instead show a warning instead of doing nothing. I hope #179 gets implemented soon.

**Comment by negamaxi** [comment]
@mkg20001 cover input should get focus immediately in this scenario. I'll check this.

**Comment by negamaxi** [comment]
Cover focusing was broken indeed. Should be fixed in [2.0.2](https://github.com/pathephone/pathephone-desktop/releases/tag/v2.0.2), check it out.

**Comment by davidak** [comment]
Saving does also nothing on my system. I'm running the AppImage v2.2.1.

First i had no Cover image. The box got red, but i haven't seen it because i had scrolled down. After adding one image, it still does nothing.

There are published albums without a cover. This should not be needed.

Do i have to open my firewall using port forwarding? I have 0 pathephone peers. Or ist just no one using this?

![screenshot from 2018-09-23 06-37-00](https://user-images.githubusercontent.com/91113/45924243-595aed00-befb-11e8-853c-8552e292c53a.png)
